Webseite aktualisieren Datenschutz
FUB-HCC/20-SWP-CodingOpenness pull request #219
Opened 2020-07-09 10:36 UTC by Erdanf

Please remember the / Bitte beachte die [Contribution Guidelines](https://github.com/FUB-HCC/20-SWP-CodingOpenness/blob/master/CONTRIBUTION.md) :heart:

## What does this PR do?
Erster Entwurf für das Design auf der Webseite

Todo's aus dem Issue
- [x] Einbinden des Prototyps + Beschreibung
- [x] Textanpassung 
- [ ]  How to Implement Anleitung
- [ ]  Recherche Findings (wie bereitet man Data Privacy Information ordentliche auf) UND Aktivitäten in dem offiziellen Repo 

## Recommendations for testing

## Links to relevant issues or information

Closes #216

2020-07-12 12:58 UTC, Erdanf commented
Ich habe nochmal die Wiki Page zur Webseite hinzugefügt.
@linuxhelf kannst du dan nochmal ein fachliches review machen, dann kann das denke ich gemerged werden, da wir ja nur noch im Wiki arbeiten werden (#216)

2020-07-12 13:38 UTC, linuxhelf commented
@Erdanf ich glaube das kann so noch nicht gemergt werden
die Performance ist nicht die beste, da wäre es evtl. schön, wenn es ein klick to load (oder wie man das nennt) gibt, damit diese unterseite auch auf schwächeren Geräten gut läuft (ich kann aber notfalls auch ohne leben)
des weiteren stimmt die platzierung noch nicht, wenn das display schmaler ist, überlappt es mit dem Text => Text nicht mehr lesbar oder ist zu breit auf mobilen geräten

2020-07-12 14:06 UTC, linuxhelf commented
ich habe den Prototypen mal klick to play gemacht, das Bild was vorher angezeigt wird, könnte man evtl. noch mit einem play button ausstatten um das klarer zu machen
das überlappen habe ich auch gefixt, hier könnte man noch probieren die height in dem Fall richtig zusetzen, damit das iframe nicht im Format 1:3 angezeigt wird

2020-07-12 15:51 UTC, julizet commented
Ihr habt ja schon einen Menge getan! Ich lese nochmal Lektorat für die bereits veröffentlichten Wiki-Pages und würde schauen, dass die Formulierungen und die Formattierung passt. 
Zudem: da Felix sich noch nicht gemeldet hat und Claas/Linux den Prototypen schon auf der Website eingebunden haben und wir nur noch auf den confirm des PR warten, würde ich mich über eine kleine Doku der Aktivitäten im offiziellem Repo kümmern.

So ist auch direkt klar, wer was zur Präsentation sagt

2020-07-13 10:09 UTC, Erdanf commented
Danke @linuxhelf für das review, das click to load funktioniert sehr gut, hab noch eine kleinen Button ins Bild gemacht. 
Ansonsten hab ich versucht das mit dem Format zu fixen. Jetzt wird es wenigstens auf dn Patz auf den Bildschirm reduziert, der ist zwar nicht immer 1:2, so wie wir es haben wollen, aber ist gut genug denke ich.

2020-07-14 17:36 UTC, Hod04 commented
![Screen Capture_select-area_20200714193311](https://user-images.githubusercontent.com/37866119/87457664-09d23d80-c609-11ea-8eca-0ea1e6427f8a.png)
- the GET request is responded with a 401
- Implementation doesn't fit mobile screen

2020-07-14 17:37 UTC, omerhod requested changes
- current implementation doesn't work for me, plus, add error handling.
- add media queries for smaller screens

2020-07-14 18:26 UTC, Erdanf commented
I added the media Querrys to rezize the iframe. 
I also get this 401 Error from "state" , but the Prototype works regardless.

2020-07-14 19:53 UTC, omerhod approved these changes

2020-07-14 19:53 UTC, merged